DOCUMENT_COPRUS = 'dd$document$$doc'
OBSERVATION_CORPUS = 'dd$observation$$doc'
INSIGHT_CORPUS = 'dd$insight$$doc'
LESSON_CORPUS = 'dd$lesson$$doc'
DD_LINK = 'dd$$link'
DD_ATTACHMENT = 'dd$$attachment'
DD_SETTING = 'dd$$setting'